name = "YAPPcore"
author = "OfficiallySp"
version = "1.21-1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbc7cc8bf4c939c7c3be38c199a7b9410c604a60a030350f8c727bab5c0fe327"

[versions]
minecraft = "1.21"
quilt = "0.26.3"
